export const types = {
    //SYNC
    FILL_POSTS:  'FILL_POSTS',
    CREATE_POST: 'CREATE_POST',

    //ASYNC
    FETCH_POSTS_ASYNC: 'FETCH_POSTS_ASYNC',
    CREATE_POST_ASYNC: 'CREATE_POST_ASYNC',
};
